### ISSUE TITLE
C(5.5) Improve explanation of migrations

### ISSUE THREAD

**Issue by ricayanzon** [uhasker/getting-things-done-in-next-js#115]
I think the concept of migrations can be misunderstood by junior devs, i.e. they could wonder why you don't just have a drizzle function to alter the table, similar to how it was done in the previous examples in the database directly using SQL. More than just helping you to update a table, migrations are beneficial because they allow version control (e.g. for rollbacks), consistency/reproducibility between your current state and that of others, and are a form of documentation. 
Also, for readers that try out stuff while reading, the table that is created in that example should already exist. I'd be a small change but better imo if a new table name is used.

**Comment by uhasker** [comment]
We also have to improve the example of conducting a migration etc. After some notes/messages from other devs, I think I'll have to invest the time to make major improvements to C5.5.
