### ISSUE TITLE
Outdated Clerk Middleware

### ISSUE THREAD

**Issue by uwumarogie** [uhasker/getting-things-done-in-next-js#138]
**Describe the bug**
There is no exported member **authMiddleware** in the @clerk/nextjs module , causing an import error in the current **middleware.ts**

**Expected behavior**
The middleware should correctly import and use the updated Clerk middleware functionality.

**Additional Notes**
If applicable, add screenshots, error messages etc. to help explain the problem.
The existing middleware.ts file is outdated. Please check out [Clerk's Next.js tutorial](https://clerk.com/docs/quickstarts/nextjs) for correct file.

**Comment by uhasker** [comment]
Authentication has been removed anyway since it's out of scope in this book and we've decided it's better to not explain explain something at all than to explain it poorly (especially if it's a topic with so many foot guns).
